  import 'package:flutter_music_ui/models/audio_file_model.dart';
  import 'package:flutter_music_ui/ui/utils/image_constants.dart';

  final List<AudioFile> musicList = [
    AudioFile(
      id: 1,
      image: ImageConstant.imgImage17,
      musicName: "Perfect",
      musicArtist: "Ed Sheeran",
      path: 'assets/Ed Sheeran – Perfect.mp3',
      time: '4:23',
      isFavourite: false,
    ),
    AudioFile(
      id: 2,
      image: ImageConstant.imgImage1760x64,
      musicName: "Blinding Lights",
      musicArtist: "The Weeknd",
      path: 'assets/The Weeknd – Blinding Lights.mp3',
      time: '3:20',
      isFavourite: false,
    ),
    AudioFile(
      id: 3,
      image: ImageConstant.imgImage171,
      musicName: "Say You",
      musicArtist: "Doja Cat",
      path: 'assets/Doja Cat – Say So.mp3',
      time: '3:58',
      isFavourite: false,
    ),
    AudioFile(
      id: 4,
      image: ImageConstant.imgImage174,
      musicName: "Shape Of You",
      musicArtist: "Ed Sheeran",
      path: 'assets/Ed Sheeran – Shape of You.mp3',
      time: '3:53',
      isFavourite: false,
    ),
    AudioFile(
      id: 5,
      image: ImageConstant.imgImage175,
      musicName: "Loop Loop",
      musicArtist: "BTS",
      path: 'assets/Death Grips - Get Got.mp3',
      time: '2:52',
      isFavourite: false,
    ),
    AudioFile(
      id: 6,
      image: ImageConstant.imgRectangle36,
      musicName: "Loop Loop",
      musicArtist: "BTS",
      path: 'assets/Death Grips - Get Got.mp3',
      time: '2:52',
      isFavourite: false,
    ),
    AudioFile(
      id: 7,
      image: ImageConstant.imgRectangle36,
      musicName: "Universo",
      musicArtist: "Astrix & Rising Dus",
      path: 'assets/Dan Balan – Crazy Loop (Mm-ma-ma).mp3',
      time: '3:17',
      isFavourite: false,
    ),
    AudioFile(
      id: 8,
      image: ImageConstant.imgImage173,
      musicName: "Ice Cream",
      musicArtist: "Blackpink ft Selena",
      path: 'assets/BLACKPINK, Selena Gomez – Ice Cream.mp3',
      time: '2:55',
      isFavourite: false,
    ),
    AudioFile(
        id: 9,
        image: ImageConstant.imgImage172,
        musicName: "Girlfriend",
        musicArtist: "Charlie Puth",
        path: 'assets/Charlie Puth – Girlfriend.mp3',
        time: '2,57',
      isFavourite: false,),

    AudioFile(
      id: 10,
      image: ImageConstant.imgImage17,
      musicName: "Perfect",
      musicArtist: "Ed Sheeran",
      path: 'assets/Ed Sheeran – Perfect.mp3',
      time: '4:23',
      isFavourite: false,
    ),
  ];
